[project]
name = "nie-intro-geospatial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "torch>=2.9.1",
    "torchgeo[datasets]>=0.7.2",
    "torchvision>=0.24.1",
]
